---
- name: Create tmux configuration for root
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: '/root/.tmux.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Create tmux configuration for voc
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: '/home/voc/.tmux.conf'
    owner: 'voc'
    group: 'voc'
    mode: 'u=rw,g=r,o=r'

- name: Create vimrc configuration per defined user
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: "{{ usr.home | default('/home/' + usr.name) }}/.tmux.conf"
    owner: "{{ usr.name }}"
    group: "{{ usr.name }}"
    mode: '0640'
  loop: "{{ users__voc_users }}"
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr
  when: usr.state | default ('present') == 'present'
