---
- name: Create Groups for users
  become: true
  ansible.builtin.group:
    name: "{{ usr.name }}"
    state: 'present'
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr
  loop: "{{ users__voc_users }}"
  when: usr.state | default ('present') == 'present'

- name: Create User for users
  become: true
  ansible.builtin.user:
    name: "{{ usr.name }}"
    group: "{{ usr.name }}"
    groups: "{{ 'admin' if usr.admin | default(false) else '' }}"
    state: 'present'
    create_home: "{{ usr.create_home | default(true) }}"
    comment: "{{ usr.comment | default(usr.name) }}"
    shell: "{{ usr.shell | default('/bin/bash') }}"
    password: "{{ usr.password | default() }}"
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr
  when: usr.state | default ('present') == 'present'
  loop: "{{ users__voc_users }}"

- name: Set Admin SSH Keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ usr.name }}"
    state: present
    key: "{{ usr.pubkeys }}"
    exclusive: true
  loop: "{{ users__voc_users }}"
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr

- name: Remove Accounts for Users
  become: true
  ansible.builtin.user:
    name: "{{ usr.name }}"
    state: 'absent'
    remove: "{{ usr.remove | default(false) }}"
  loop: "{{ users__voc_users }}"
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr
  when: usr.state | default ('present') == 'absent'

- name: Remove Groups for Users
  become: true
  ansible.builtin.group:
    name: "{{ usr.name }}"
    state: 'absent'
  loop: "{{ users__voc_users }}"
  loop_control:
    label: "user={{ usr.name }}"
    loop_var: usr
  when: usr.state | default ('present') == 'absent'
